# Generated by Django 4.0.5 on 2022-06-07 07:05

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post',
            field=tinymce.models.HTMLField(null=True),
        ),
    ]
