# Generated by Django 4.0.5 on 2022-06-06 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manuz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.RemoveField(
            model_name='post',
            name='date_posted',
        ),
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
    ]
